version: '3'

tasks:
  zip-*:
    desc: "Zip lab directory ready for submission."
    vars:
      FOLDER: "lab{{index .MATCH 0}}"
    dir: "{{.FOLDER}}"
    cmds:
      - mkdir -p ../zips
      - cp ../Dockerfile .
      - defer: rm -f Dockerfile
      - cp ../run.sh .
      - defer: rm -f ./run.sh
      - zip -r ../zips/{{.FOLDER}}.zip $(git ls-files) $(git ls-files --others --exclude-standard)
    preconditions:
      - sh: uv run --directory {{.FOLDER}} python -m unittest discover -v -s tests
        msg: "One or more unit tests are failing, fix before zipping."
      - sh: ls {{.FOLDER}}/*.pdf
        msg: "Lab report not present, add before zipping."
    silent: false

  docker-*:
    desc: "Check Docker works."
    vars:
      FOLDER: "lab{{index .MATCH 0}}"
    dir: "{{.FOLDER}}"
    cmds:
      - cp ../Dockerfile .
      - defer: rm -f Dockerfile
      - cp ../run.sh .
      - defer: rm -f ./run.sh
      - ./run.sh

  mypy-*:
    desc: "Check mypy."
    vars:
      FOLDER: "lab{{index .MATCH 0}}"
    dir: "{{.FOLDER}}"
    cmds:
      - uv run mypy src
      - uv run mypy tests