version: '3'

tasks:
  zip-*:
    desc: "Zip lab directory ready for submission."
    deps: [mkdir_zips]
    vars:
      FOLDER: "lab{{index .MATCH 0}}"
    dir: "{{.FOLDER}}"
    cmds:
      - cp ../Dockerfile .
      - defer: rm -f Dockerfile
      - cp ../run.sh .
      - defer: rm -f ./run.sh
      - zip -r ../zips/{{.FOLDER}}.zip $(git ls-files) $(git ls-files --others --exclude-standard)
    preconditions:
      - sh: uv run --directory {{.FOLDER}} python -m unittest discover -v -s tests
        msg: "One or more unit tests are failing, fix before zipping."
      - sh: ls {{.FOLDER}}/*.pdf
        msg: "Lab report not present, add before zipping."
    silent: false
  
  mkdir_zips:
    cmds: 
      - mkdir -p zips