[project]
name = "lab1"
version = "0.1.0"
description = "Primitives, Diffie-Hellman, Signatures"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "pytest-sugar>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
