[project]
name = "lab1"
version = "0.1.0"
description = "Primitives, Diffie-Hellman, Signatures"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pynacl>=1.5.0",
    "pytest>=8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
