[project]
name = "lab2"
version = "0.1.0"
description = "Authenticated key exchange"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
