[project]
name = "lab3"
version = "0.1.0"
description = "Private information retrieval"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
